### ISSUE TITLE
Version on pip is not the latest

### ISSUE THREAD

**Issue by mariomadproductions** [arkrow/PyMusicLooper#23] opened 2023-10-18 15:32 UTC
Despite https://pypi.org/project/pymusiclooper/ showing 3.1.0, installing it with pipx and running `pymusiclooper --version` tells you that 2.5.3 is installed.

My current workaround: downloading the repo, running `poetry install`, aliasing `pymusiclooper` to `poetry --directory [repo directory] run -q pymusiclooper`, although poetry has to startup each time, which is slow, so this isn't that great a workaround.

**Comment by mariomadproductions** [comment] 2023-10-18 19:23
That's not the case I'm afraid. pipx even says "installed package pymusiclooper 2.5.3" when I run `pipx install pymusiclooper`.

**Comment by arkrow** [comment] 2023-10-18 19:50
Which python version are you using? PyMusicLooper versions >=3.0 support Python 3.9 - 3.11. If you have a lower version, I imagine that is most likely why it is installing 2.5.3, since that is the last version compatible with Python 3.6 and above.

**Comment by mariomadproductions** [comment] 2023-10-18 20:02
Ah I see. Unfortunately I get this error when specifying the python version. Although I guess this is a pipx issue?
```
$ pipx install pymusiclooper --python $(which python3.11)
/usr/bin/pipx:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
Error: Command '['/home/user/.local/pipx/venvs/pymusiclooper/bin/python3.11', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
'/usr/bin/python3.11 -m venv /home/user/.local/pipx/venvs/pymusiclooper' failed
```

**Comment by arkrow** [comment] 2023-10-18 20:36
Since pipx was installed using a relatively outdated Python version, I'd assume pipx is also on a lower version for compatibility reasons. If you need the older Python installation, you can use something like [pyenv](https://github.com/pyenv/pyenv) to manage your python versions. Uninstall pymusiclooper and pipx (if PyMusicLooper was the only library installed using it), switch python versions using pyenv and follow the installation as normal, namely: 
```bash
pip install pipx
pipx ensurepath
pipx install pymusiclooper
```

I believe that should be the simplest and least disruptive solution to the problem.

**Comment by arkrow** [comment] 2023-10-23 15:41
Since the problem is related to your machine's environment, rather than an issue with PyMusicLooper itself, I will be closing this issue.

**Closed** 2023-10-23 15:42 UTC
